### ISSUE TITLE
mcm query failure

### ISSUE THREAD

**Issue by kpedro88** [dmwm/dasgoclient#20]
The following query works on the DAS web interface, but not with dasgoclient. Here is the error I get:
```
dasgoclient -query="mcm dataset=/WJetsToLNu_HT-100to200_Tune4C_13TeV-madgraph-tauola/Fall13-POSTLS162_V1-v1/GEN-SIM" 
panic: interface conversion: interface {} is []interface {}, not []mongo.DASRecord

goroutine 1 [running]:
main.checkDASrecords(0xc420146068, 0x1, 0x1, 0x0)
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.03/dasgoclient/main.go:122 +0x38a
main.process(0x7ffcb5d13318, 0x5f, 0x0, 0x873228, 0x1, 0x1, 0x0, 0x0, 0x879e0d, 0x16, ...)
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.03/dasgoclient/main.go:457 +0x1dea
main.main()
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.03/dasgoclient/main.go:105 +0x899
```

I am using the latest version:
```
Build: git=v02.00.03 go=go1.9.4 date=2018-06-25 17:13:17.220373118 -0500 CDT m=+0.008666305
```

**Comment by vkuznet** [comment]
Kevin,
this is fixed and submitted to CMSSW, see progress at https://github.com/cms-sw/cmsdist/pull/4156
Best,
Valentin.

**Comment by kpedro88** [comment]
Thanks!

**Comment by heitorPB** [comment]
I also have the same problem:

```
$ dasgoclient -query "mcm dataset=/BBH_HToTauTau_M_125_TuneZ2star_8TeV_pythia6_tauola/Summer12_DR53X-PU_S10_START53_V19-v1/AODSIM"
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.getRecords(0xc42018e058, 0x1, 0x1, 0xc42040a220, 0x1, 0x1, 0xc42040a280, 0x1, 0x1, 0x8740c8, ...)
	/afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.06/dasgoclient/main.go:656 +0x12ee
main.process(0x7ffd3efc14f0, 0x6b, 0x0, 0x8740c8, 0x1, 0x1, 0x0, 0x0, 0x87af94, 0x16, ...)
	/afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.06/dasgoclient/main.go:526 +0x25bd
main.main()
	/afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v02.00.06/dasgoclient/main.go:105 +0x899
```

I'm using dasgoclient in lxplus

```
$ dasgoclient --version
Build: git=v02.00.06 go=go1.9.6 date=2018-08-27 16:39:45.664232808 +0200 CEST m=+0.008242386
```

@vkuznet the PR you mentioned didn't solve this

**Comment by vkuznet** [comment]
It is different issue (when no mcm info is found). I fixed in github tree and
will propagate this fix into CMSSW today/tomorrow.

**Comment by vkuznet** [comment]
See this fix progress in
https://github.com/cms-sw/cmsdist/pull/4289/
